name: v-a-l-e-r-i-e
favicon: null
layout_spectrum: 0.7413975119125098
typography_spectrum: 0.7661250336095691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.5502034483943135
  saturation: 0.9405284221284091
  rhythmicContrast: 0.298025066498667
purpose: []
